## Case Study problem 1 in Numpy

#### 1.Create a function that takes dimensions as tuples e.g.,(3,3) and a numeric value and returns a numpy array of the given dimension filled with the given value e.g.:solve((3,3),5) will return
[
    [5,5,5],
    [5,5,5],
    [5,5,5]
 ]

In [1]:
import numpy as np

In [9]:
a=np.full(9,5).reshape(3,3)
a

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

#### 2.Create a method that takes n numpy arrays of same dimensions sums them and return the answer.

In [10]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [12]:
b=np.sum(mat)
b

325

#### 3. Given a 2D array of NxM dimension,write a function that accepts this array as well as two numbers N and M.The method should return the top-left NxM sub matrix e.g:
[
    [1,2,3],
    [4,5,6],
    [7,8,9]
  ]

In [13]:
N=np.arange(1,10).reshape(3,3)
N

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### top_left_sub_matrix(matrix,2,2)-> should return:
[
    [1,2]
    [4,5]
 ]

In [121]:
c=N[:2,:2]
c

array([[1, 2],
       [4, 5]])

#### 4. Given a 2D array of NxM dimension,write a function that accepts this array as well as two numbers N and M.The method should return the bottom-right NxM sub matrix e.g:
[
    [1,2,3],
    [4,5,6],
    [7,8,9]
  ]

In [55]:
M=np.arange(1,10).reshape(3,3)
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### sub_matrix(matrix,1,1)-> should return:(keep in mind these arrays are zero indexed)
[
    [5,6]
    [8,9]
 ]

In [133]:
d=M[1:,1:]
d

array([[5, 6],
       [8, 9]])

#### 5.Given a 1D numpy array.write a function that accept this array as parameters.The method should return a dictionary with 'mean' and 'std_dev' as key and array's mean and array's standard deviation as values
[1,1,1]
#### solution(arr)-> should return:
#### {'mean':1.0,'std_dev':0.0}


In [2]:
arr=np.ones(3).astype(int)
arr

array([1, 1, 1])

In [21]:
def function(arr):
    arrays_mean=arr.mean()
    arrays_standard_deviation=arr.std()
    dic={'mean':arrays_mean,'std_dev':arrays_standard_deviation}
    return dic

In [23]:
function(arr) 

{'mean': 1.0, 'std_dev': 0.0}