## Numpy Assignment 2

In [2]:
import numpy as np

#### 1.Create a 3x3 Matrix,range 2 to 10

In [2]:
arr=np.arange(2,11).reshape(3,3)
arr

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

####  2.Create a numpy array and convert integer into float

In [3]:
a=[1,2,3,4]

In [4]:
np.array(a).astype(float)

array([1., 2., 3., 4.])

#### 3.Numpy program to append values to the end of an array

In [4]:
b=np.array([10,20,30])

In [5]:
c=np.array([40,50,60,70,80,90])

In [6]:
d=np.concatenate((b,c),axis=0) 

In [7]:
print(d)

[10 20 30 40 50 60 70 80 90]


#### 4.Create 2 numpy arrays and add the elements of both the arrays and store the result in sumArray.

In [8]:
arr1=np.array([30,40,50,60])
arr2=np.array([10,20,30,40])
sumArray=arr1+arr2

In [9]:
print(sumArray)

[ 40  60  80 100]


#### 5.Create a 3*3 array having values from 10-90(interval of 10) and store that in array1.
#### perform the following tasks:

In [22]:
array1=np.arange(10,100,10).reshape(3,3)

In [23]:
array1

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

#### a.Extract the 1st row from the array

In [26]:
array1[0:1][0:2]

array([[10, 20, 30]])

#### b.Extract the last element from the array

In [27]:
array1[2][2]

90